# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright (C) 2021 ImmortalWrt.org

name: Update Mirror

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 */8 * * *

jobs:
  update-mirror:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - master
      fail-fast: false
      max-parallel: 1

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Init Compilation Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install build-essential libncurses5-dev binutils bzip2 coreutils gawk gettext git patch zlib1g-dev subversion git-core gcc g++ p7zip-full libssl-dev autoconf automake libtool autopoint curl wget vim nano python3 python3-pip xz-utils tar unzip rsync
          sudo -E apt-get -qq clean

      - name: Checkout ImmortalWrt Source Tree on Branch ${{ matrix.branch }}
        uses: actions/checkout@v3
        with:
          repository: "immortalwrt/immortalwrt"
          ref: ${{ matrix.branch }}
          path: "immortalwrt"

      - name: Update Feeds
        run: |
          cd "immortalwrt"
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Download Packages
        run: |
          cd "immortalwrt"
          echo -e "CONFIG_ALL=y" > ".config"
          make defconfig
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: Fetch Cached Uploaded Files List
        uses: actions/cache@v3
        with:
          path: "uploaded-files"
          key: immortalwrt-mirror-uploaded-${{ matrix.branch }}-${{ github.run_id }}
          restore-keys: |
            immortalwrt-mirror-uploaded-

      - name: Fetch Cached Uploader Keys
        uses: actions/cache@v3
        with:
          path: "uploader-keys"
          key: immortalwrt-mirror-uploader-${{ github.run_id }}
          restore-keys: |
            immortalwrt-mirror-uploader-

      - name: Upload Files to ImmortalWrt Download Server
        env:
          RSYNC_ADDR: ${{ secrets.RSYNC_ADDR }}
          RSYNC_USER: ${{ secrets.RSYNC_USER }}
          RSYNC_PASSWORD: ${{ secrets.RSYNC_PASS }}
        run: |
          find 'immortalwrt/dl/' -maxdepth 1 -type f -not -size 0 -not -name '.*' -not -name '*.hash' -not -name '*.dl' -printf '%f\n' > 'sourcelist'
          rsync --files-from="sourcelist" --size-only --delay-updates --partial-dir=".~tmp~$GITHUB_RUN_ID" -ahv "immortalwrt/dl/" "rsync://${RSYNC_USER}@${RSYNC_ADDR}/dl/"

      - name: Upload Files to OSDN
        uses: Pendect/action-rsyncer@9738db02560c333bf629a1533bd86ceda138e599
        with:
          flags: '-ahv'
          options: '--files-from=sourcelist --size-only --delay-updates --partial-dir=.~tmp~${{ env.GITHUB_RUN_ID }}'
          src: 'immortalwrt/dl/'
          dest: '${{ secrets.OSDN_USER }}@storage.osdn.net:/storage/groups/i/im/immortalwrt/sources/'
        env:
          DEPLOY_KEY: ${{ secrets.OSDN_KEY }}

      - name: Upload Files to OneDrive
        env:
          ODRS_REFRESH_TOKEN: ${{ secrets.ODRS_REFRESH_TOKEN }}
          UPLOADER_TYPE: "onedrive"
          UPLOADER_CONF: "uploader.json"
        run: |
          ./uploader-cache/detect-upload-files.sh
          [ "$(ls -A "package-sources"/* | wc -l)" -gt "0" ] || exit 0
          [ -f "uploader-keys/$UPLOADER_TYPE.json" ] && cp -f "uploader-keys/$UPLOADER_TYPE.json" "$UPLOADER_CONF" || ./onedrive-uploader/gen-onedriveconf.sh
          ./onedrive-uploader/OneDriveUploader -f -c "$UPLOADER_CONF" -s "package-sources" -r "/" -skip
          ./uploader-cache/gen-downloaded-hash.sh
          [ -d "uploader-keys" ] || mkdir -p "uploader-keys"
          cp -f "$UPLOADER_CONF" "uploader-keys/$UPLOADER_TYPE.json"

  cleanup-workflow-runs:
    runs-on: ubuntu-latest
    needs: update-mirror
    steps:
      - name: Cleanup Workflow Runs
        uses: GitRML/delete-workflow-runs@v1.2.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
